'use client'

import { FileText } from 'lucide-react'
import { listReports } from '@/lib/api/client'
import { useAsync } from '@/lib/use-async'
import { ErrorState, TableSkeleton } from '@/components/data-states'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { formatDateTime } from '@/lib/format'

export function ReportsView() {
  const reports = useAsync(() => listReports(), [])

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h2 className="text-lg font-semibold tracking-tight">Reports</h2>
        <p className="text-sm text-muted-foreground">
          Generated assessment reports — backed by the Flask service at <span className="font-mono">GET /api/reports</span>.
        </p>
      </div>

      <Card>
        <CardContent className="p-0">
          {reports.loading ? (
            <div className="p-4">
              <TableSkeleton rows={5} />
            </div>
          ) : reports.error ? (
            <div className="p-4">
              <ErrorState message={reports.error.message} onRetry={reports.reload} />
            </div>
          ) : !reports.data || reports.data.length === 0 ? (
            <div className="flex flex-col items-center gap-2 py-16 text-center">
              <FileText className="size-8 text-muted-foreground" aria-hidden="true" />
              <p className="text-sm font-medium">No reports yet</p>
              <p className="max-w-sm text-sm text-muted-foreground">
                Import a scan via <span className="font-medium">Import Scan</span> — a report is generated at
                <span className="font-mono"> POST /report/upload</span> and appears here.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[720px] text-sm">
                <thead>
                  <tr className="border-b border-border text-left text-xs text-muted-foreground">
                    <th className="px-4 py-3 font-medium">Report</th>
                    <th className="px-4 py-3 font-medium">Scan</th>
                    <th className="px-4 py-3 font-medium">Generated by</th>
                    <th className="px-4 py-3 font-medium">Generated</th>
                    <th className="px-4 py-3 font-medium">Status</th>
                    <th className="px-4 py-3 font-medium">Size</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.data.map((r) => (
                    <tr key={r.id} className="border-b border-border/60 last:border-0 hover:bg-muted/30">
                      <td className="px-4 py-3 font-mono text-xs">{r.id.slice(0, 8)}</td>
                      <td className="px-4 py-3 font-medium">{r.scanName || r.scanId}</td>
                      <td className="px-4 py-3 text-muted-foreground">{r.generatedBy}</td>
                      <td className="px-4 py-3 text-muted-foreground">{formatDateTime(r.generatedAt)}</td>
                      <td className="px-4 py-3">
                        <Badge variant={r.status === 'ready' ? 'default' : 'secondary'}>{r.status}</Badge>
                      </td>
                      <td className="px-4 py-3 font-mono tabular-nums">
                        {r.sizeKb != null ? `${r.sizeKb} KB` : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
